function English() {
	document.getElementById("welcomeBach-text").innerHTML="<i>Your daily dose of counterpoint</i><br><br>Amid the quarentine, I decided to listen to all the musical work of J.S. Bach. Dissatisfied with my previous attempts to fully explore a repertoire consistently, I solved the problem with a <i>Python</i> script.<br><br>The project is compatible with *nix systems in general, and consists of a draw, to be carried out daily, of a Bachian piece not yet heard, providing a list of YouTube links to listen to recordings of it.<br><br>Being a free software, welcomeBach can be downloaded, modified or shared based on the users' interests (under the terms of the GNU GPLv2), and its code is hosted on <a href=\"https://github.com/ofefo/welcomeBach\" target=\"_blank\">GitHub</a>. As a future perspective, I intend to expand the repertoire with other composers whose work is similarly cataloged.<br><br>Contributions are welcome!";
	document.getElementById("emersao-text").innerHTML="<i>Soundscape composition</i><br><br>As they get closer to the surface, divers hear sounds transmuting...<br><br>December 2019";
	document.getElementById("ping-desc").innerHTML="<i>Interactive audiovisual system controled by musical improvisation</i><br>Developed with Caio Campos";
	document.getElementById("ping-text").innerHTML="PING is inpired by PONG, the classic ATARI game, reworked as an audiovisual system that interacts with musical improvisation, so that each side of this ping-pong is controlled by a musician who, instead of playing with a joystick (or racket), uses his instrument.<br><br> As in the original game, PING is a competition between two sides, but here, these sides can invert, multiply, expand and contract, or even bounce around the screen... and all this movement is controlled by the players with melodies, intensities and rhythms.<br><br>The dispute for points provides a stimulus for experimentation and musical expressiveness, while different levels and sound responses behave in unexpected ways, disturbing the internal logic of the game and weaving more layers in the interaction between musicians and the system.";
	document.getElementById("agora-desc").innerHTML="<i>Game for improvisation ensemble</i>";
	document.getElementById("agora-text").innerHTML="<br>Inspired by the Greek institution that is the symbol of Athenian democracy, <i>agora</i> invites musicians to a musical assembly in which there is freedom to discuss any subject, provided that all participants have space for their voice to be heard.<br><br> The piece was written in October 2019 and premiered by the ensemble <i>Sonante 21</i> in the same month, in a concert conducted by Stephan Froleyks, in a project that involved scores written in just one day and with maximum of one page.<br>";
	document.getElementById("agora-rec").innerHTML="<br>The following recording is a realization of the piece by the ensemble <i>GILU</i>, in a concert at the first <i>FIM: Festival Improvisada Música</i>, in November 2019.<br><a href=\"./mus/agora.png\" target=\"_blank\">Score</a>";
	document.getElementById("decampo-text").innerHTML="<i>Selected field recordings</i><br><br>Listening the space between a <i>chirp</i> here and a <i>vroom</i> there.<br><br>Recorded in Vitória/ES and Belo Horizonte/MG.<br>January - March 2019";
	document.getElementById("carnaval-text").innerHTML="<i>Festive noise</i><br><br>Teaser for <a href=\"https://www.youtube.com/watch?v=jEP_jgpSgaY\" target=\"_blank\">Blitzkrieg Noise #08</a><br><br>March 2019";
	document.getElementById("bifurcacoes-text").innerHTML="<i>Flute and live-electronics</i><br><br>You hear a high-pitched and syllabic music in the back and forth of the wind, foggy with leaves and distance. In this imaginary garden, time will perpetually fork into innumerable futures, revealing mirrored paths. Even though everything is decided at the moment, it will always be possible to listen to the past.<br><br>Inspired by the short story <i>The garden of forking paths</i> by Jorge Luis Borges.<br><br>Premiered by Rodrigo Frade at EBA-UFMG's Art Gallery.<br>December 2018";
	document.getElementById("bifurcacoes-rec").innerHTML="Reduced stereo version:";
	document.getElementById("praca6-text").innerHTML="<i>Noise music in a public square</i><br><br>Solo and duo improvised with Quasicrystal at Praça Sete (Belo Horizonte/MG), as part of the series \"<a href=\"https://www.youtube.com/watch?v=N65vxKMwXaI&list=PLhl6QLuwAA5HuX4UJheqv5SDjsWdt0jX9\" target=\"_blank\">Praça 6</a>\".<br><br>Played with SBOX (a joystick mapped as a digital instrument), a contact microphone and guitar pedals.<br><br>Recording and cover photo by Henrique Iwao.<br>Quasicrystal is Sannanda Acácia.<br>June 2018";
	document.getElementById("dysgraphia-text").innerHTML="<i>Defective acusmatic</i><br><br>Acoustic and synthesized sounds associate handwriting, typing, object manipulation and failures in electronic devices, seeking poetic coherence amid imperfection.<br><br>March 2018";
	document.getElementById("maestrandom-desc").innerHTML="<i>Musical instructions randomizer</i>";
	document.getElementById("maestrandom-text").innerHTML="Thought for a performance with the ensemble <i>GILU</i>. Keywords are chosen in random time intervals, coordenating the improvisation with some level of unpredictability. At the same time, instrumental groups are chosen at each minute to execute those ideas. The keywords were suggested by the ensemble members.";
	document.getElementById("maestrandom-patch").innerHTML="<a href=\"./maestro.pd\" download=\"maestro.pd\">Patch download (.pd)</a>";
	document.getElementById("cadaeco-text").innerHTML="<i>Soundscapes of chaos and cosiness<br>at an urban cave</i><br><br>Superposition of everyday sounds and instrumental improvisations. Featuring Luís Israel in \"chamada perdida\".<br><br>Recorded with a smartphone.<br>Cover photo by Arthur Moreira.<br>July - December 2015";
	document.getElementById("quatrocordas-text").innerHTML="<i>Four short improvisations with a guitar lacking two strings</i><br><br>Recorded with the computer microphone.<br>Cover in watercolor on paper<br>and digital editing.<br>May 2015";
}
